package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT")
public class Account implements java.io.Serializable {

	private Integer id;
	private String name;
	private String contactPersonName;
	private String contactPersonPhone;
	private int contactInfoId;
	private Byte active;
	private Set users = new HashSet(0);

	public Account() {
	}

	public Account(int contactInfoId) {
		this.contactInfoId = contactInfoId;
	}

	public Account(String name, String contactPersonName, String contactPersonPhone, int contactInfoId, Byte active,
			Set users) {
		this.name = name;
		this.contactPersonName = contactPersonName;
		this.contactPersonPhone = contactPersonPhone;
		this.contactInfoId = contactInfoId;
		this.active = active;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CONTACT_PERSON_NAME", length = 45)
	public String getContactPersonName() {
		return this.contactPersonName;
	}

	public void setContactPersonName(String contactPersonName) {
		this.contactPersonName = contactPersonName;
	}

	@Column(name = "CONTACT_PERSON_PHONE", length = 11)
	public String getContactPersonPhone() {
		return this.contactPersonPhone;
	}

	public void setContactPersonPhone(String contactPersonPhone) {
		this.contactPersonPhone = contactPersonPhone;
	}

	@Column(name = "CONTACT_INFO_ID", nullable = false)
	public int getContactInfoId() {
		return this.contactInfoId;
	}

	public void setContactInfoId(int contactInfoId) {
		this.contactInfoId = contactInfoId;
	}

	@Column(name = "ACTIVE")
	public Byte getActive() {
		return this.active;
	}

	public void setActive(Byte active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
