package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BackupDoctors generated by hbm2java
 */
@Entity
@Table(name = "BACKUP_DOCTORS")
public class BackupDoctors implements java.io.Serializable {

	private int doctorId;
	private String doctorName;
	private String speciality;
	private String marketClass;
	private String address;
	private String center;
	private String districtName;
	private String districtId;
	private String governorate;
	private String phone;
	private String mobile;
	private String nearestPharmacy;
	private String workingMorningPlace;
	private String serial;

	public BackupDoctors() {
	}

	public BackupDoctors(int doctorId) {
		this.doctorId = doctorId;
	}

	public BackupDoctors(int doctorId, String doctorName, String speciality, String marketClass, String address,
			String center, String districtName, String districtId, String governorate, String phone, String mobile,
			String nearestPharmacy, String workingMorningPlace, String serial) {
		this.doctorId = doctorId;
		this.doctorName = doctorName;
		this.speciality = speciality;
		this.marketClass = marketClass;
		this.address = address;
		this.center = center;
		this.districtName = districtName;
		this.districtId = districtId;
		this.governorate = governorate;
		this.phone = phone;
		this.mobile = mobile;
		this.nearestPharmacy = nearestPharmacy;
		this.workingMorningPlace = workingMorningPlace;
		this.serial = serial;
	}

	@Id

	@Column(name = "DOCTOR_ID", unique = true, nullable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "DOCTOR_NAME")
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "SPECIALITY", length = 45)
	public String getSpeciality() {
		return this.speciality;
	}

	public void setSpeciality(String speciality) {
		this.speciality = speciality;
	}

	@Column(name = "MARKET_CLASS", length = 45)
	public String getMarketClass() {
		return this.marketClass;
	}

	public void setMarketClass(String marketClass) {
		this.marketClass = marketClass;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CENTER")
	public String getCenter() {
		return this.center;
	}

	public void setCenter(String center) {
		this.center = center;
	}

	@Column(name = "DISTRICT_NAME")
	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	@Column(name = "DISTRICT_ID", length = 45)
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	@Column(name = "GOVERNORATE")
	public String getGovernorate() {
		return this.governorate;
	}

	public void setGovernorate(String governorate) {
		this.governorate = governorate;
	}

	@Column(name = "PHONE")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "MOBILE")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "NEAREST_PHARMACY")
	public String getNearestPharmacy() {
		return this.nearestPharmacy;
	}

	public void setNearestPharmacy(String nearestPharmacy) {
		this.nearestPharmacy = nearestPharmacy;
	}

	@Column(name = "WORKING_MORNING_PLACE")
	public String getWorkingMorningPlace() {
		return this.workingMorningPlace;
	}

	public void setWorkingMorningPlace(String workingMorningPlace) {
		this.workingMorningPlace = workingMorningPlace;
	}

	@Column(name = "SERIAL", length = 45)
	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

}
