package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "DISTRICT")
public class District implements java.io.Serializable {

	private Integer id;
	private Governorate governorate;
	private String arName;
	private String enName;
	private Set employeesCoveredDistricts = new HashSet(0);
	private Set contacts = new HashSet(0);
	private Set doctors = new HashSet(0);

	public District() {
	}

	/**
	 * @param id
	 */
	public District(Integer id) {
		this.id = id;
	}

	public District(Governorate governorate) {
		this.governorate = governorate;
	}

	public District(Governorate governorate, String arName, String enName, Set employeesCoveredDistricts, Set contacts,
			Set doctors) {
		this.governorate = governorate;
		this.arName = arName;
		this.enName = enName;
		this.employeesCoveredDistricts = employeesCoveredDistricts;
		this.contacts = contacts;
		this.doctors = doctors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GOVERNORATE_ID", nullable = false)
	public Governorate getGovernorate() {
		return this.governorate;
	}

	public void setGovernorate(Governorate governorate) {
		this.governorate = governorate;
	}

	@Column(name = "AR_NAME", length = 45)
	public String getArName() {
		return this.arName;
	}

	public void setArName(String arName) {
		this.arName = arName;
	}

	@Column(name = "EN_NAME", length = 45)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<EmployeesCoveredDistrict> getEmployeesCoveredDistricts() {
		return this.employeesCoveredDistricts;
	}

	public void setEmployeesCoveredDistricts(Set employeesCoveredDistricts) {
		this.employeesCoveredDistricts = employeesCoveredDistricts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<ServiceProvider> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set doctors) {
		this.doctors = doctors;
	}

}
