package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE")
public class Employee implements java.io.Serializable {

	private int id;
	private Contact contact;
	private Employee manager;
	private String employeeJobTitle;
	private String employeeNumber;
	private Account account;
	private Set users = new HashSet(0);
	private Set employeesCoveredDistricts = new HashSet(0);
	private Set employeesServiceProviders = new HashSet(0);
	private Set visitsForEmployeeId = new HashSet(0);
	private Set schedulesForEmployeeId = new HashSet(0);
	private Set managers = new HashSet(0);
	private Set schedulesForSubordinateId = new HashSet(0);
	private Set schedulesForManagerId = new HashSet(0);
	private Set visitsForSubordinateId = new HashSet(0);

	public Employee() {
	}

	public Employee(int id) {
		this.id = id;
	}

	public Employee(int id, Contact contact, Employee manager, String employeeJobTitle,
			String employeeNumber, Set users, Set employeesCoveredDistricts, Set employeesServiceProviders, Set visitsForEmployeeId,
			Set schedulesForEmployeeId, Set managers, Set schedulesForSubordinateId, Set schedulesForManagerId,Set visitsForSubordinateId) {
		this.id = id;
		this.contact = contact;
		this.manager = manager;
		this.employeeJobTitle = employeeJobTitle;
		this.employeeNumber = employeeNumber;
		this.users = users;
		this.employeesCoveredDistricts = employeesCoveredDistricts;
		this.employeesServiceProviders = employeesServiceProviders;
		this.visitsForEmployeeId = visitsForEmployeeId;
		this.schedulesForEmployeeId = schedulesForEmployeeId;
		this.managers = managers;
		this.schedulesForSubordinateId = schedulesForSubordinateId;
		this.schedulesForManagerId = schedulesForManagerId;
		this.visitsForSubordinateId = visitsForSubordinateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	/**
	 * @return the contact
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTACT_ID")
	public Contact getContact() {
		return contact;
	}

	/**
	 * @param contact the contact to set
	 */
	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGER_ID")
	public Employee getManager() {
		return this.manager;
	}

	public void setManager(Employee manager) {
		this.manager = manager;
	}
	
	@Column(name = "JOB_TITLE", length = 45)
	public String getEmployeeJobTitle() {
		return employeeJobTitle;
	}

	public void setEmployeeJobTitle(String employeeJobTitle) {
		this.employeeJobTitle = employeeJobTitle;
	}

	@Column(name = "EMPLOYEE_NUMBER", length = 45)
	public String getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<EmployeesCoveredDistrict> getEmployeesCoveredDistricts() {
		return this.employeesCoveredDistricts;
	}

	public void setEmployeesCoveredDistricts(Set employeesCoveredDistricts) {
		this.employeesCoveredDistricts = employeesCoveredDistricts;
	}

	/**
	 * @return the employeesDoctor
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<EmployeeServiceProvider> getEmployeeServiceProviders() {
		return employeesServiceProviders;
	}

	/**
	 * @param employeesDoctor the employeesDoctor to set
	 */
	public void setEmployeeServiceProviders(Set employeesServiceProviders) {
		this.employeesServiceProviders = employeesServiceProviders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeByEmployeeId")
	public Set<Visit> getVisitsForEmployeeId() {
		return this.visitsForEmployeeId;
	}

	public void setVisitsForEmployeeId(Set visitsForEmployeeId) {
		this.visitsForEmployeeId = visitsForEmployeeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeByEmployeeId")
	public Set<Schedule> getSchedulesForEmployeeId() {
		return this.schedulesForEmployeeId;
	}

	public void setSchedulesForEmployeeId(Set schedulesForEmployeeId) {
		this.schedulesForEmployeeId = schedulesForEmployeeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manager")
	public Set<Employee> getManagers() {
		return this.managers;
	}

	public void setManagers(Set managers) {
		this.managers = managers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeBySubordinateId")
	public Set<Schedule> getSchedulesForSubordinateId() {
		return this.schedulesForSubordinateId;
	}

	public void setSchedulesForSubordinateId(Set schedulesForSubordinateId) {
		this.schedulesForSubordinateId = schedulesForSubordinateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeByManagerId", cascade=CascadeType.ALL)
	public Set<Schedule> getSchedulesForManagerId() {
		return schedulesForManagerId;
	}

	public void setSchedulesForManagerId(Set schedulesForManagerId) {
		this.schedulesForManagerId = schedulesForManagerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeBySubordinateId")
	public Set<Visit> getVisitsForSubordinateId() {
		return this.visitsForSubordinateId;
	}

	public void setVisitsForSubordinateId(Set visitsForSubordinateId) {
		this.visitsForSubordinateId = visitsForSubordinateId;
	}

}
