package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Governorate generated by hbm2java
 */
@Entity
@Table(name = "GOVERNORATE")
public class Governorate implements java.io.Serializable {

	private Integer id;
	private String arName;
	private String enName;
	private Set districts = new HashSet(0);
	private Set contacts = new HashSet(0);

	public Governorate() {
	}

	/**
	 * @param id
	 */
	public Governorate(Integer id) {
		this.id = id;
	}

	public Governorate(Set districts, Set contacts) {
		this.districts = districts;
		this.contacts = contacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "AR_NAME", length = 45)
	public String getArName() {
		return this.arName;
	}

	public void setArName(String arName) {
		this.arName = arName;
	}

	@Column(name = "EN_NAME", length = 45)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "governorate")
	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set districts) {
		this.districts = districts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "governorate")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

}
