package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "PERMISSION")
public class Permission implements java.io.Serializable, com.dashda.data.entities.Entity {

	private Integer id;
	private String name;
	private String permission;
	private PermissionType permissionType;
	private Set userRolePermissions = new HashSet(0);

	public Permission() {
	}

	/**
	 * @param name
	 * @param permission
	 * @param permissionType
	 */
	public Permission(String name, String permission, PermissionType permissionType) {
		super();
		this.name = name;
		this.permission = permission;
		this.permissionType = permissionType;
	}

	public Permission(String name, String permission, Set userRolePermissions) {
		this.name = name;
		this.permission = permission;
		this.userRolePermissions = userRolePermissions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PERMISSION", length = 45)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSION_TYPE_ID")
	public PermissionType getPermissionType() {
		return permissionType;
	}

	public void setPermissionType(PermissionType permissionType) {
		this.permissionType = permissionType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<UserRolePermission> getUserRolePermissions() {
		return this.userRolePermissions;
	}

	public void setUserRolePermissions(Set userRolePermissions) {
		this.userRolePermissions = userRolePermissions;
	}
	
	

}
