package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "SCHEDULE")
public class Schedule implements java.io.Serializable {

	private Integer id;
	private Doctor doctor;
	private Employee employeeByEmployeeId;
	private Employee employeeBySubordinateId;
	private Employee employeeByManagerId;
	private ScheduleStatus scheduleStatus;
	private Date datetime;

	public Schedule() {
	}

	public Schedule(Integer id) {
		super();
		this.id = id;
	}

	public Schedule(Doctor doctor, Employee employeeByEmployeeId, Employee employeeBySubordinateId,
			Employee employeeByManagerID, ScheduleStatus scheduleStatus, Date datetime) {
		this.doctor = doctor;
		this.employeeByEmployeeId = employeeByEmployeeId;
		this.employeeBySubordinateId = employeeBySubordinateId;
		this.employeeByManagerId = employeeByManagerID;
		this.scheduleStatus = scheduleStatus;
		this.datetime = datetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false, updatable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUTOR_ID")
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployeeByEmployeeId() {
		return this.employeeByEmployeeId;
	}

	public void setEmployeeByEmployeeId(Employee employeeByEmployeeId) {
		this.employeeByEmployeeId = employeeByEmployeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBORDINATE_ID")
	public Employee getEmployeeBySubordinateId() {
		return this.employeeBySubordinateId;
	}

	public void setEmployeeBySubordinateId(Employee employeeBySubordinateId) {
		this.employeeBySubordinateId = employeeBySubordinateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGER_ID")
	public Employee getEmployeeByManagerId() {
		return employeeByManagerId;
	}

	public void setEmployeeByManagerId(Employee employeeByManagerId) {
		this.employeeByManagerId = employeeByManagerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHEDULE_STATUS_ID")
	public ScheduleStatus getScheduleStatus() {
		return this.scheduleStatus;
	}

	public void setScheduleStatus(ScheduleStatus scheduleStatus) {
		this.scheduleStatus = scheduleStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
