package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ScheduleStatus generated by hbm2java
 */
@Entity
@Table(name = "SCHEDULE_STATUS")
public class ScheduleStatus implements java.io.Serializable {

	private int id;
	private String name;
	private Set schedules = new HashSet(0);

	public ScheduleStatus() {
	}

	public ScheduleStatus(int id) {
		this.id = id;
	}

	public ScheduleStatus(int id, String name, Set schedules) {
		this.id = id;
		this.name = name;
		this.schedules = schedules;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleStatus")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

}
