package com.dashda.data.entities;
// Generated Apr 4, 2018 2:50:44 PM by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_PROVIDER")
public class ServiceProvider implements java.io.Serializable, com.dashda.data.entities.BaseEntity {

	private Integer id;
	private String arName;
	private String enName;
	private String arContactPersonName;
	private String enContactPersonName;
	private ServiceProviderType serviceProviderType;
	private Speciality speciality;
	private Governorate governorate;
	private District district;
	private ServiceProviderGrade ServiceProviderGrade;
	private String arAddress;
	private String enAddress;
	private int active;
	
	private Set schedules = new HashSet(0);
	private Set visits = new HashSet(0);
	private Set employeeServiceProviders = new HashSet(0);
	
	public ServiceProvider() {
	}

	public ServiceProvider(int id) {
		this.id = id;
	}



	/**
	 * @param id
	 * @param arName
	 * @param enName
	 * @param arContactPersonName
	 * @param enContactPersonName
	 * @param serviceProviderType
	 * @param speciality
	 * @param governorate
	 * @param district
	 * @param grade
	 * @param arAddress
	 * @param enAddress
	 * @param active
	 * @param schedules
	 * @param visits
	 * @param employeesDoctors
	 */
	public ServiceProvider(int id, String arName, String enName, String arContactPersonName, String enContactPersonName,
			ServiceProviderType serviceProviderType, Speciality speciality, Governorate governorate, District district,
			ServiceProviderGrade ServiceProviderGrade, String arAddress, String enAddress, int active, Set schedules, Set visits,
			Set employeeServiceProviders) {
		super();
		this.id = id;
		this.arName = arName;
		this.enName = enName;
		this.arContactPersonName = arContactPersonName;
		this.enContactPersonName = enContactPersonName;
		this.serviceProviderType = serviceProviderType;
		this.speciality = speciality;
		this.governorate = governorate;
		this.district = district;
		this.ServiceProviderGrade = ServiceProviderGrade;
		this.arAddress = arAddress;
		this.enAddress = enAddress;
		this.active = active;
		this.schedules = schedules;
		this.visits = visits;
		this.employeeServiceProviders = employeeServiceProviders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false, updatable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "AR_NAME", length = 100)
	public String getArName() {
		return arName;
	}

	public void setArName(String arName) {
		this.arName = arName;
	}

	@Column(name = "EN_NAME", length = 100)
	public String getEnName() {
		return enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "AR_CONTACT_PERSON_NAME", length = 100)
	public String getArContactPersonName() {
		return arContactPersonName;
	}

	public void setArContactPersonName(String arContactPersonName) {
		this.arContactPersonName = arContactPersonName;
	}

	@Column(name = "EN_CONTACT_PERSON_NAME", length = 100)
	public String getEnContactPersonName() {
		return enContactPersonName;
	}

	public void setEnContactPersonName(String enContactPersonName) {
		this.enContactPersonName = enContactPersonName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICE_PROVIDER_TYPE_ID")
	public ServiceProviderType getServiceProviderType() {
		return serviceProviderType;
	}

	public void setServiceProviderType(ServiceProviderType serviceProviderType) {
		this.serviceProviderType = serviceProviderType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPECIALTY_ID")
	public Speciality getSpeciality() {
		return this.speciality;
	}

	public void setSpeciality(Speciality speciality) {
		this.speciality = speciality;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GOVERNORATE_ID")
	public Governorate getGovernorate() {
		return governorate;
	}

	public void setGovernorate(Governorate governorate) {
		this.governorate = governorate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRICT_ID")
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICE_PROVIDER_GRADE_ID")
	public ServiceProviderGrade getServiceProviderGrade() {
		return ServiceProviderGrade;
	}

	public void setServiceProviderGrade(ServiceProviderGrade ServiceProviderGrade) {
		this.ServiceProviderGrade = ServiceProviderGrade;
	}

	@Column(name = "AR_ADDRESS", length = 100)
	public String getArAddress() {
		return arAddress;
	}

	public void setArAddress(String arAddress) {
		this.arAddress = arAddress;
	}

	@Column(name = "EN_ADDRESS", length = 100)
	public String getEnAddress() {
		return enAddress;
	}

	public void setEnAddress(String enAddress) {
		this.enAddress = enAddress;
	}

	@Column(name = "ACTIVE")
	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceProvider")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceProvider")
	public Set<Visit> getVisits() {
		return this.visits;
	}

	public void setVisits(Set visits) {
		this.visits = visits;
	}

	/**
	 * @return the employeesDoctor
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceProvider")
	public Set<EmployeeServiceProvider> getEmployeeServiceProviders() {
		return employeeServiceProviders;
	}

	/**
	 * @param employeesDoctor the employeesDoctor to set
	 */
	public void setEmployeeServiceProviders(Set employeeServiceProvider) {
		this.employeeServiceProviders = employeeServiceProvider;
	}
	
	

}
